name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore: [ "README.md" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache npm
        id: cache-npm
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if : steps.cache-npm.outputs.cache-hit != 'true'
        if : steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run tests
        id: test
        run: npm test 
        id: test
        run: npm test 

      - name: Upload build artifacts
        if: success() && steps.test.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
      - name: Upload build artifacts
        if: success() && steps.test.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if : steps.cache-npm.outputs.cache-hit != 'true'
        if : steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run build
        run: npm run build

  report:
    needs: [build]
    if: failure()
    name: Report Failure
    runs-on: ubuntu-latest
    steps:
      -name: Output failure message
      run: |
        echo "Some went wrong"
        echo "${GITHUB_WORKFLOW} failed on ${{ github.event_name }} for ${{ github.repository }} at commit ${{ github.sha }}"